// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheBackfield.Data;

#nullable disable

namespace the_backfield.Migrations
{
    [DbContext(typeof(TheBackfieldDbContext))]
    [Migration("20241212010927_InterceptedAtNullable")]
    partial class InterceptedAtNullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlayerPosition", b =>
                {
                    b.Property<int>("PlayersId")
                        .HasColumnType("integer");

                    b.Property<int>("PositionsId")
                        .HasColumnType("integer");

                    b.HasKey("PlayersId", "PositionsId");

                    b.HasIndex("PositionsId");

                    b.ToTable("PlayerPosition");
                });

            modelBuilder.Entity("TheBackfield.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("AwayTeamScore")
                        .HasColumnType("integer");

                    b.Property<int>("GamePeriods")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GameStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("HomeTeamScore")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodLength")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("TheBackfield.Models.GameStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FumblesCommitted")
                        .HasColumnType("integer");

                    b.Property<int>("FumblesForced")
                        .HasColumnType("integer");

                    b.Property<int>("FumblesRecovered")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("InterceptionsReceived")
                        .HasColumnType("integer");

                    b.Property<int>("InterceptionsThrown")
                        .HasColumnType("integer");

                    b.Property<int>("PassAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("PassCompletions")
                        .HasColumnType("integer");

                    b.Property<int>("PassYards")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceivingYards")
                        .HasColumnType("integer");

                    b.Property<int>("Receptions")
                        .HasColumnType("integer");

                    b.Property<int>("RushAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("RushYards")
                        .HasColumnType("integer");

                    b.Property<int>("Tackles")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Touchdowns")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("GameStats");
                });

            modelBuilder.Entity("TheBackfield.Models.Penalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoFirstDown")
                        .HasColumnType("boolean");

                    b.Property<int?>("BasePenaltyId")
                        .HasColumnType("integer");

                    b.Property<bool>("LossOfDown")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NoPlay")
                        .HasColumnType("boolean");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Yardage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Penalties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Penalty",
                            NoPlay = true,
                            Yardage = 0
                        },
                        new
                        {
                            Id = 2,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Chop Block",
                            NoPlay = true,
                            Yardage = 15
                        },
                        new
                        {
                            Id = 3,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Clipping",
                            NoPlay = true,
                            Yardage = 15
                        },
                        new
                        {
                            Id = 4,
                            AutoFirstDown = true,
                            LossOfDown = false,
                            Name = "Defensive Holding",
                            NoPlay = true,
                            Yardage = 5
                        },
                        new
                        {
                            Id = 5,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Defensive Offside",
                            NoPlay = true,
                            Yardage = 5
                        },
                        new
                        {
                            Id = 6,
                            AutoFirstDown = true,
                            LossOfDown = false,
                            Name = "Defensive Pass Interference",
                            NoPlay = true,
                            Yardage = 0
                        },
                        new
                        {
                            Id = 7,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Defensive Too Many Men on Field",
                            NoPlay = true,
                            Yardage = 5
                        },
                        new
                        {
                            Id = 8,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Delay of Game",
                            NoPlay = true,
                            Yardage = 5
                        },
                        new
                        {
                            Id = 9,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Encroachment",
                            NoPlay = true,
                            Yardage = 5
                        },
                        new
                        {
                            Id = 10,
                            AutoFirstDown = true,
                            LossOfDown = false,
                            Name = "Facemask",
                            NoPlay = true,
                            Yardage = 15
                        },
                        new
                        {
                            Id = 11,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Fair Catch Interference",
                            NoPlay = true,
                            Yardage = 15
                        },
                        new
                        {
                            Id = 12,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "False Start",
                            NoPlay = true,
                            Yardage = 5
                        },
                        new
                        {
                            Id = 13,
                            AutoFirstDown = true,
                            LossOfDown = false,
                            Name = "Hip-Drop Tackle",
                            NoPlay = true,
                            Yardage = 15
                        },
                        new
                        {
                            Id = 14,
                            AutoFirstDown = true,
                            LossOfDown = false,
                            Name = "Horse-Collar Tackle",
                            NoPlay = true,
                            Yardage = 15
                        },
                        new
                        {
                            Id = 15,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Illegal Block in the Back",
                            NoPlay = true,
                            Yardage = 10
                        },
                        new
                        {
                            Id = 16,
                            AutoFirstDown = true,
                            LossOfDown = false,
                            Name = "Illegal Contact",
                            NoPlay = true,
                            Yardage = 5
                        },
                        new
                        {
                            Id = 17,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Illegal Formation",
                            NoPlay = true,
                            Yardage = 5
                        },
                        new
                        {
                            Id = 18,
                            AutoFirstDown = false,
                            LossOfDown = true,
                            Name = "Illegal Forward Pass",
                            NoPlay = true,
                            Yardage = 5
                        },
                        new
                        {
                            Id = 19,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Illegal Kicking Loose Ball",
                            NoPlay = true,
                            Yardage = 10
                        },
                        new
                        {
                            Id = 20,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Illegal Motion",
                            NoPlay = true,
                            Yardage = 5
                        },
                        new
                        {
                            Id = 21,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Illegal Shift",
                            NoPlay = true,
                            Yardage = 5
                        },
                        new
                        {
                            Id = 22,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Illegal Substitution",
                            NoPlay = true,
                            Yardage = 5
                        },
                        new
                        {
                            Id = 23,
                            AutoFirstDown = false,
                            LossOfDown = true,
                            Name = "Illegal Touch - Player Out of Bounds",
                            NoPlay = true,
                            Yardage = 0
                        },
                        new
                        {
                            Id = 24,
                            AutoFirstDown = false,
                            LossOfDown = true,
                            Name = "Illegal Touch - Ineligible Receiver",
                            NoPlay = true,
                            Yardage = 5
                        },
                        new
                        {
                            Id = 25,
                            AutoFirstDown = true,
                            LossOfDown = false,
                            Name = "Illegal Use of Hands",
                            NoPlay = true,
                            Yardage = 10
                        },
                        new
                        {
                            Id = 26,
                            AutoFirstDown = true,
                            LossOfDown = false,
                            Name = "Impermissible Use of the Helmet",
                            NoPlay = true,
                            Yardage = 15
                        },
                        new
                        {
                            Id = 27,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Ineligible Player Downfield",
                            NoPlay = true,
                            Yardage = 5
                        },
                        new
                        {
                            Id = 28,
                            AutoFirstDown = false,
                            LossOfDown = true,
                            Name = "Intentional Grounding",
                            NoPlay = true,
                            Yardage = 10
                        },
                        new
                        {
                            Id = 29,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Invalid Fair Catch Signal",
                            NoPlay = true,
                            Yardage = 5
                        },
                        new
                        {
                            Id = 30,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Kickoff Out of Bounds",
                            NoPlay = true,
                            Yardage = 0
                        },
                        new
                        {
                            Id = 31,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Leaping",
                            NoPlay = true,
                            Yardage = 15
                        },
                        new
                        {
                            Id = 32,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Neutral Zone Infraction",
                            NoPlay = true,
                            Yardage = 5
                        },
                        new
                        {
                            Id = 33,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Offensive Holding",
                            NoPlay = true,
                            Yardage = 10
                        },
                        new
                        {
                            Id = 34,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Offensive Offside",
                            NoPlay = true,
                            Yardage = 5
                        },
                        new
                        {
                            Id = 35,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Offensive Pass Interference",
                            NoPlay = true,
                            Yardage = 10
                        },
                        new
                        {
                            Id = 36,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Offensive Too Many Men on Field",
                            NoPlay = true,
                            Yardage = 5
                        },
                        new
                        {
                            Id = 37,
                            AutoFirstDown = true,
                            LossOfDown = false,
                            Name = "Roughing the Kicker",
                            NoPlay = true,
                            Yardage = 15
                        },
                        new
                        {
                            Id = 38,
                            AutoFirstDown = true,
                            LossOfDown = false,
                            Name = "Roughing the Passer",
                            NoPlay = false,
                            Yardage = 15
                        },
                        new
                        {
                            Id = 39,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Running into the Kicker",
                            NoPlay = true,
                            Yardage = 5
                        },
                        new
                        {
                            Id = 40,
                            AutoFirstDown = false,
                            LossOfDown = false,
                            Name = "Taunting",
                            NoPlay = false,
                            Yardage = 15
                        },
                        new
                        {
                            Id = 41,
                            AutoFirstDown = true,
                            LossOfDown = false,
                            Name = "Tripping",
                            NoPlay = true,
                            Yardage = 15
                        },
                        new
                        {
                            Id = 42,
                            AutoFirstDown = true,
                            LossOfDown = false,
                            Name = "Unnecessary Roughness",
                            NoPlay = false,
                            Yardage = 15
                        },
                        new
                        {
                            Id = 43,
                            AutoFirstDown = true,
                            LossOfDown = false,
                            Name = "Unsportsmanlike Conduct",
                            NoPlay = false,
                            Yardage = 15
                        });
                });

            modelBuilder.Entity("TheBackfield.Models.Play", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClockEnd")
                        .HasColumnType("integer");

                    b.Property<int?>("ClockStart")
                        .HasColumnType("integer");

                    b.Property<int>("Down")
                        .HasColumnType("integer");

                    b.Property<int?>("FieldPositionEnd")
                        .HasColumnType("integer");

                    b.Property<int?>("FieldPositionStart")
                        .HasColumnType("integer");

                    b.Property<int?>("GameId")
                        .HasColumnType("integer");

                    b.Property<int?>("GamePeriod")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PrevPlayId")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int?>("ToGain")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PrevPlayId");

                    b.HasIndex("TeamId");

                    b.ToTable("Plays");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Down = 0,
                            Notes = "Game Start"
                        });
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.Conversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DefensiveConversion")
                        .HasColumnType("boolean");

                    b.Property<bool>("Good")
                        .HasColumnType("boolean");

                    b.Property<int?>("PasserId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReturnerId")
                        .HasColumnType("integer");

                    b.Property<int?>("RusherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PasserId");

                    b.HasIndex("PlayId")
                        .IsUnique();

                    b.HasIndex("ReceiverId");

                    b.HasIndex("ReturnerId");

                    b.HasIndex("RusherId");

                    b.ToTable("Conversions");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.ExtraPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DefensiveConversion")
                        .HasColumnType("boolean");

                    b.Property<bool>("Fake")
                        .HasColumnType("boolean");

                    b.Property<bool>("Good")
                        .HasColumnType("boolean");

                    b.Property<int?>("KickerId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReturnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KickerId");

                    b.HasIndex("PlayId")
                        .IsUnique();

                    b.HasIndex("ReturnerId");

                    b.ToTable("ExtraPoints");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.FieldGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Fake")
                        .HasColumnType("boolean");

                    b.Property<bool>("Good")
                        .HasColumnType("boolean");

                    b.Property<int?>("KickerId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KickerId");

                    b.HasIndex("PlayId")
                        .IsUnique();

                    b.ToTable("FieldGoals");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.Fumble", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FumbleCommittedById")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("FumbleForcedById")
                        .HasColumnType("integer");

                    b.Property<int?>("FumbleRecoveredById")
                        .HasColumnType("integer");

                    b.Property<int>("FumbledAt")
                        .HasColumnType("integer");

                    b.Property<int>("PlayId")
                        .HasColumnType("integer");

                    b.Property<int>("RecoveredAt")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FumbleCommittedById");

                    b.HasIndex("FumbleForcedById");

                    b.HasIndex("FumbleRecoveredById");

                    b.HasIndex("PlayId");

                    b.ToTable("Fumbles");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.Interception", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("InterceptedAt")
                        .HasColumnType("integer");

                    b.Property<int?>("InterceptedById")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int>("PlayId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InterceptedById");

                    b.HasIndex("PlayId")
                        .IsUnique();

                    b.ToTable("Interceptions");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.KickBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BlockedById")
                        .HasColumnType("integer");

                    b.Property<int>("PlayId")
                        .HasColumnType("integer");

                    b.Property<int?>("RecoveredAt")
                        .HasColumnType("integer");

                    b.Property<int?>("RecoveredById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlockedById");

                    b.HasIndex("PlayId")
                        .IsUnique();

                    b.HasIndex("RecoveredById");

                    b.ToTable("KickBlocks");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.Kickoff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("FieldedAt")
                        .HasColumnType("integer");

                    b.Property<int?>("KickerId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReturnerId")
                        .HasColumnType("integer");

                    b.Property<bool>("Touchback")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("KickerId");

                    b.HasIndex("PlayId")
                        .IsUnique();

                    b.HasIndex("ReturnerId");

                    b.ToTable("Kickoffs");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.Lateral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarriedTo")
                        .HasColumnType("integer");

                    b.Property<int?>("NewCarrierId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int>("PlayId")
                        .HasColumnType("integer");

                    b.Property<int?>("PossessionAt")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NewCarrierId");

                    b.HasIndex("PlayId");

                    b.ToTable("Laterals");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.Pass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completion")
                        .HasColumnType("boolean");

                    b.Property<int?>("PasserId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PasserId");

                    b.HasIndex("PlayId")
                        .IsUnique();

                    b.HasIndex("ReceiverId");

                    b.ToTable("Passes");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.PassDefense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DefenderId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DefenderId");

                    b.HasIndex("PlayId");

                    b.ToTable("PassDefenses");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.PlayPenalty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoFirstDown")
                        .HasColumnType("boolean");

                    b.Property<bool>("Enforced")
                        .HasColumnType("boolean");

                    b.Property<int>("EnforcedFrom")
                        .HasColumnType("integer");

                    b.Property<bool>("LossOfDown")
                        .HasColumnType("boolean");

                    b.Property<bool>("NoPlay")
                        .HasColumnType("boolean");

                    b.Property<int>("PenaltyId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayId")
                        .HasColumnType("integer");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("Yardage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PenaltyId");

                    b.HasIndex("PlayId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayPenalties");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.Punt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("FairCatch")
                        .HasColumnType("boolean");

                    b.Property<bool>("Fake")
                        .HasColumnType("boolean");

                    b.Property<int?>("FieldedAt")
                        .HasColumnType("integer");

                    b.Property<int?>("KickerId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReturnerId")
                        .HasColumnType("integer");

                    b.Property<bool>("Touchback")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("KickerId");

                    b.HasIndex("PlayId")
                        .IsUnique();

                    b.HasIndex("ReturnerId");

                    b.ToTable("Punts");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.Rush", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayId")
                        .HasColumnType("integer");

                    b.Property<int?>("RusherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayId")
                        .IsUnique();

                    b.HasIndex("RusherId");

                    b.ToTable("Rushes");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.Tackle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayId")
                        .HasColumnType("integer");

                    b.Property<int?>("TacklerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayId");

                    b.HasIndex("TacklerId");

                    b.ToTable("Tackles");
                });

            modelBuilder.Entity("TheBackfield.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("Hometown")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TheBackfield.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "QB",
                            Name = "Quarterback"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "RB",
                            Name = "Running Back"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "HB",
                            Name = "Halfback"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "FB",
                            Name = "Fullback"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "WR",
                            Name = "Wide Receiver"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "TE",
                            Name = "Tight End"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "OL",
                            Name = "Offensive Line"
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "C",
                            Name = "Center"
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "OG",
                            Name = "Offensive Guard"
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "LG",
                            Name = "Left Guard"
                        },
                        new
                        {
                            Id = 11,
                            Abbreviation = "RG",
                            Name = "Right Guard"
                        },
                        new
                        {
                            Id = 12,
                            Abbreviation = "OT",
                            Name = "Offensive Tackle"
                        },
                        new
                        {
                            Id = 13,
                            Abbreviation = "LT",
                            Name = "Left Tackle"
                        },
                        new
                        {
                            Id = 14,
                            Abbreviation = "RT",
                            Name = "Right Tackle"
                        },
                        new
                        {
                            Id = 15,
                            Abbreviation = "DL",
                            Name = "Defensive Line"
                        },
                        new
                        {
                            Id = 16,
                            Abbreviation = "NT",
                            Name = "Nose Tackle"
                        },
                        new
                        {
                            Id = 17,
                            Abbreviation = "DE",
                            Name = "Defensive End"
                        },
                        new
                        {
                            Id = 18,
                            Abbreviation = "DT",
                            Name = "Defensive Tackle"
                        },
                        new
                        {
                            Id = 19,
                            Abbreviation = "LB",
                            Name = "Linebacker"
                        },
                        new
                        {
                            Id = 20,
                            Abbreviation = "ILB",
                            Name = "Inside Linebacker"
                        },
                        new
                        {
                            Id = 21,
                            Abbreviation = "MLB",
                            Name = "Middle Linebacker"
                        },
                        new
                        {
                            Id = 22,
                            Abbreviation = "OLB",
                            Name = "Outside Linebacker"
                        },
                        new
                        {
                            Id = 23,
                            Abbreviation = "EDGE",
                            Name = "Edge Rusher"
                        },
                        new
                        {
                            Id = 24,
                            Abbreviation = "CB",
                            Name = "Cornerback"
                        },
                        new
                        {
                            Id = 25,
                            Abbreviation = "S",
                            Name = "Safety"
                        },
                        new
                        {
                            Id = 26,
                            Abbreviation = "FS",
                            Name = "Free Safety"
                        },
                        new
                        {
                            Id = 27,
                            Abbreviation = "SS",
                            Name = "Strong Safety"
                        },
                        new
                        {
                            Id = 28,
                            Abbreviation = "P",
                            Name = "Punter"
                        },
                        new
                        {
                            Id = 29,
                            Abbreviation = "PK",
                            Name = "Place Kicker"
                        },
                        new
                        {
                            Id = 30,
                            Abbreviation = "LS",
                            Name = "Long Snapper"
                        });
                });

            modelBuilder.Entity("TheBackfield.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorPrimaryHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorSecondaryHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeField")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("TheBackfield.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SessionStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlayerPosition", b =>
                {
                    b.HasOne("TheBackfield.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBackfield.Models.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBackfield.Models.Game", b =>
                {
                    b.HasOne("TheBackfield.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBackfield.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("TheBackfield.Models.GameStat", b =>
                {
                    b.HasOne("TheBackfield.Models.Game", null)
                        .WithMany("GameStats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBackfield.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBackfield.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBackfield.Models.Play", b =>
                {
                    b.HasOne("TheBackfield.Models.Game", "Game")
                        .WithMany("Plays")
                        .HasForeignKey("GameId");

                    b.HasOne("TheBackfield.Models.Play", "PrevPlay")
                        .WithMany()
                        .HasForeignKey("PrevPlayId");

                    b.HasOne("TheBackfield.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("Game");

                    b.Navigation("PrevPlay");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.Conversion", b =>
                {
                    b.HasOne("TheBackfield.Models.Player", "Passer")
                        .WithMany()
                        .HasForeignKey("PasserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TheBackfield.Models.Play", "Play")
                        .WithOne("Conversion")
                        .HasForeignKey("TheBackfield.Models.PlayEntities.Conversion", "PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBackfield.Models.Player", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TheBackfield.Models.Player", "Returner")
                        .WithMany()
                        .HasForeignKey("ReturnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TheBackfield.Models.Player", "Rusher")
                        .WithMany()
                        .HasForeignKey("RusherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Passer");

                    b.Navigation("Play");

                    b.Navigation("Receiver");

                    b.Navigation("Returner");

                    b.Navigation("Rusher");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.ExtraPoint", b =>
                {
                    b.HasOne("TheBackfield.Models.Player", "Kicker")
                        .WithMany()
                        .HasForeignKey("KickerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TheBackfield.Models.Play", "Play")
                        .WithOne("ExtraPoint")
                        .HasForeignKey("TheBackfield.Models.PlayEntities.ExtraPoint", "PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBackfield.Models.Player", "Returner")
                        .WithMany()
                        .HasForeignKey("ReturnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kicker");

                    b.Navigation("Play");

                    b.Navigation("Returner");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.FieldGoal", b =>
                {
                    b.HasOne("TheBackfield.Models.Player", "Kicker")
                        .WithMany()
                        .HasForeignKey("KickerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TheBackfield.Models.Play", "Play")
                        .WithOne("FieldGoal")
                        .HasForeignKey("TheBackfield.Models.PlayEntities.FieldGoal", "PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kicker");

                    b.Navigation("Play");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.Fumble", b =>
                {
                    b.HasOne("TheBackfield.Models.Player", "FumbleCommittedBy")
                        .WithMany()
                        .HasForeignKey("FumbleCommittedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("TheBackfield.Models.Player", "FumbleForcedBy")
                        .WithMany()
                        .HasForeignKey("FumbleForcedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TheBackfield.Models.Player", "FumbleRecoveredBy")
                        .WithMany()
                        .HasForeignKey("FumbleRecoveredById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TheBackfield.Models.Play", "Play")
                        .WithMany("Fumbles")
                        .HasForeignKey("PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FumbleCommittedBy");

                    b.Navigation("FumbleForcedBy");

                    b.Navigation("FumbleRecoveredBy");

                    b.Navigation("Play");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.Interception", b =>
                {
                    b.HasOne("TheBackfield.Models.Player", "InterceptedBy")
                        .WithMany()
                        .HasForeignKey("InterceptedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("TheBackfield.Models.Play", "Play")
                        .WithOne("Interception")
                        .HasForeignKey("TheBackfield.Models.PlayEntities.Interception", "PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterceptedBy");

                    b.Navigation("Play");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.KickBlock", b =>
                {
                    b.HasOne("TheBackfield.Models.Player", "BlockedBy")
                        .WithMany()
                        .HasForeignKey("BlockedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TheBackfield.Models.Play", "Play")
                        .WithOne("KickBlock")
                        .HasForeignKey("TheBackfield.Models.PlayEntities.KickBlock", "PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBackfield.Models.Player", "RecoveredBy")
                        .WithMany()
                        .HasForeignKey("RecoveredById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BlockedBy");

                    b.Navigation("Play");

                    b.Navigation("RecoveredBy");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.Kickoff", b =>
                {
                    b.HasOne("TheBackfield.Models.Player", "Kicker")
                        .WithMany()
                        .HasForeignKey("KickerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TheBackfield.Models.Play", "Play")
                        .WithOne("Kickoff")
                        .HasForeignKey("TheBackfield.Models.PlayEntities.Kickoff", "PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBackfield.Models.Player", "Returner")
                        .WithMany()
                        .HasForeignKey("ReturnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kicker");

                    b.Navigation("Play");

                    b.Navigation("Returner");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.Lateral", b =>
                {
                    b.HasOne("TheBackfield.Models.Player", "NewCarrier")
                        .WithMany()
                        .HasForeignKey("NewCarrierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("TheBackfield.Models.Play", "Play")
                        .WithMany("Laterals")
                        .HasForeignKey("PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewCarrier");

                    b.Navigation("Play");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.Pass", b =>
                {
                    b.HasOne("TheBackfield.Models.Player", "Passer")
                        .WithMany()
                        .HasForeignKey("PasserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TheBackfield.Models.Play", "Play")
                        .WithOne("Pass")
                        .HasForeignKey("TheBackfield.Models.PlayEntities.Pass", "PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBackfield.Models.Player", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Passer");

                    b.Navigation("Play");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.PassDefense", b =>
                {
                    b.HasOne("TheBackfield.Models.Player", "Defender")
                        .WithMany()
                        .HasForeignKey("DefenderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TheBackfield.Models.Play", "Play")
                        .WithMany("PassDefenders")
                        .HasForeignKey("PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Defender");

                    b.Navigation("Play");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.PlayPenalty", b =>
                {
                    b.HasOne("TheBackfield.Models.Penalty", "Penalty")
                        .WithMany()
                        .HasForeignKey("PenaltyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBackfield.Models.Play", "Play")
                        .WithMany("Penalties")
                        .HasForeignKey("PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBackfield.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Penalty");

                    b.Navigation("Play");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.Punt", b =>
                {
                    b.HasOne("TheBackfield.Models.Player", "Kicker")
                        .WithMany()
                        .HasForeignKey("KickerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TheBackfield.Models.Play", "Play")
                        .WithOne("Punt")
                        .HasForeignKey("TheBackfield.Models.PlayEntities.Punt", "PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBackfield.Models.Player", "Returner")
                        .WithMany()
                        .HasForeignKey("ReturnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kicker");

                    b.Navigation("Play");

                    b.Navigation("Returner");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.Rush", b =>
                {
                    b.HasOne("TheBackfield.Models.Play", "Play")
                        .WithOne("Rush")
                        .HasForeignKey("TheBackfield.Models.PlayEntities.Rush", "PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBackfield.Models.Player", "Rusher")
                        .WithMany()
                        .HasForeignKey("RusherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Play");

                    b.Navigation("Rusher");
                });

            modelBuilder.Entity("TheBackfield.Models.PlayEntities.Tackle", b =>
                {
                    b.HasOne("TheBackfield.Models.Play", "Play")
                        .WithMany("Tacklers")
                        .HasForeignKey("PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBackfield.Models.Player", "Tackler")
                        .WithMany()
                        .HasForeignKey("TacklerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Play");

                    b.Navigation("Tackler");
                });

            modelBuilder.Entity("TheBackfield.Models.Player", b =>
                {
                    b.HasOne("TheBackfield.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TheBackfield.Models.Game", b =>
                {
                    b.Navigation("GameStats");

                    b.Navigation("Plays");
                });

            modelBuilder.Entity("TheBackfield.Models.Play", b =>
                {
                    b.Navigation("Conversion");

                    b.Navigation("ExtraPoint");

                    b.Navigation("FieldGoal");

                    b.Navigation("Fumbles");

                    b.Navigation("Interception");

                    b.Navigation("KickBlock");

                    b.Navigation("Kickoff");

                    b.Navigation("Laterals");

                    b.Navigation("Pass");

                    b.Navigation("PassDefenders");

                    b.Navigation("Penalties");

                    b.Navigation("Punt");

                    b.Navigation("Rush");

                    b.Navigation("Tacklers");
                });

            modelBuilder.Entity("TheBackfield.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
